# Generated by Django 4.1.5 on 2023-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('n_movies', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=225)),
            ],
        ),
    ]
